directory: watch_directory
sender_threads: 10
log_file_duration_hours: 3000
cache_file_name: file_cache.dat
bin_size: 3000000
compression: false
tags:
  DEFAULT:
    priority: 5
    transfer_method: 1
  radar:
    priority: 3
    transfer_method: 2
  laser:
    priority: 2
    transfer_method: 1
  log:
    priority: 1
    transfer_method: 1