# Path config
input_directory: /Users/dohn898/Desktop/test_location # Use absolute path
cache_file_name: file_cache.dat
logs_directory: logs
disk_path: disk
# Operating variables
sender_threads: 10
cache_write_interval: 60
disk_switching: false # true, false, or auto
bin_timeout: 3600  # bin sending timeout in seconds
# HTTP(s) setup
server_port: 8080
receiver_address: localhost:8081
tls: false
client_ssl_cert: ../../conf/client.pem
client_ssl_key: ../../conf/client.key

dynamic:
  bin_size: 300000
  compression: false
  tags:
    DEFAULT:
      priority: 5
      sort: modtime # none, modtime
      delete_on_verify: true
      transfer_method: HTTP # transfer methods: HTTP, Disk, GridFTP
    disk_test:
      priority: 5
      transfer_method: Disk
