directory: watch_directory
sender_threads: 10
log_file_duration_hours: 3000
cache_file_name: file_cache.dat
bin_size: 3000000
compression: false
disk_path: disk
# Transfer methods:
# 1 - HTTP
# 2 - Disk
# 3 - GridFTP
tags:
  DEFAULT:
    priority: 5
    transfer_method: 1
  disk_test:
    priority: 5
    transfer_method: 2